### ISSUE TITLE
Missing maintainer...

### ISSUE THREAD

**Issue by TobiX** [wummel/dosage#101]
We seem to be without a maintainer/main author/release manager, since @wummel seems to be MIA.

I would like to put in a support request to GitHub to move this project over to an organization, so it is easier to manage administrators.

I really don't want to be the lone maintainer, so I urge any contributor who reads this to contact me either vie mail (see repository), IRC (channel #dosage on FreeNode) or this ticket - so I can gauge interest.

**Comment by kierun** [comment]
I'd help.

**Comment by Manabi** [comment]
I'm willing to try to help, but the definitions still confuse me for the most part.  I have a few comics I've tried to write definitions for to no avail, so I'm not sure how much help I'd be.

**Comment by TobiX** [comment]
@Manabi: I was working on a new branch to make it easier to write comic modules (#70) and was discussing with @wummel to get it merged. Since it looks like I'm taking over the project, I will merge that work. Then it will be possible to write modules with XPath (example: 6c7fb17) or CSS (example: 6769e1eb) - The nice thing is: You can test and develop those in your browser (I'd recommend FireBug)

**Comment by Null000** [comment]
I can help. I did contribute a couple new comics a while back so I do know at least the basics about the project.

Also, yes XPath please.

**Comment by TobiX** [comment]
So GitHub doesn't want to migrate repositories without the owner's consent (which I can understand). I will fork this project into the new organization I created and copy over relevant content. After the new location is set up, I'll try to direct new users there.

**Comment by TobiX** [comment]
Please move over to the new project:

    git remote set-url origin https://github.com/webcomics/dosage.git
