### ISSUE TITLE
CtrlAltDel-Sillies

### ISSUE THREAD

**Issue by MrHappy** [wummel/dosage#96]
This one stopped downloading due to a blockage through robots.txt.
Same goes voor CtrlAltDel...
Is there a way to fix this??

**Comment by TobiX** [comment]
No, we respect robots.txt so comic authors can decide if they want to allow Dosage on their comics. Please contact the comic author and ask him/her politely if he/she would consider adding an exception for Dosage. You can refer them to http://wummel.github.io/dosage/ (or this ticket), where our policy is documented.

PS: The current robots.txt of http://www.cad-comic.com/ is quite harmful: It disallows ALL robots, so the page might disappear from search indexes and archive.org...

**Comment by MrHappy** [comment]
Thanks for the response...
